POST http://localhost:4004/api/v1/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "gabe ruh",
  "email": "garuhm3@gmail.com",
  "address": "904 harsdale way",
  "dateOfBirth": "2008-04-12",
  "registeredDate": "2008-04-12"
}